name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      uses: dtolnay/rust-toolchain@stable

    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build --release --verbose
      
    - name: Tar Artefact
      run: tar -czvf server.tar.gz ./target/release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: server
        path: server.tar.gz
